### ISSUE TITLE
Write blog post about refugees

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/blog#40]
@JosephBARBIERDARNAL we can talk about this next week, but I'm hoping to have you help me with a blog post using data from the [{refugees} package](https://populationstatistics.github.io/refugees/).  

A bit of context: https://show.rfor.us/rTYmh2km

**Comment by JosephBARBIERDARNAL** [comment]
@dgkeyes do you want me to look at it first before our call to see if I can come up with ideas for it?

**Comment by dgkeyes** [comment]
Sure, that's fine if you want to give it a shot.

**Comment by JosephBARBIERDARNAL** [comment]
I quickly realised this. It needs a few improvements (same scale, colors, general theme, etc.), but a faceted evolution (of the countries with the most refugees) seems interesting.

![refugees_evolution_facetted](https://github.com/user-attachments/assets/1eec26c3-39db-4c53-ae14-9dcd4dc56e51)

**Comment by JosephBARBIERDARNAL** [comment]
Here's a simple version that still needs a few adjustments (colors, font, etc.).

The main problem is that it's not a **per capita** measure, so nothing very meaningful in my opinion. @dgkeyes Any ideas or more specific things you'd like to see here?

![animated_refugee_map](https://github.com/user-attachments/assets/3d3d4508-8c60-4ce3-bb54-91d78c86da46)

**Comment by dgkeyes** [comment]
Thanks. I'll take a look at this soon.

**Comment by dgkeyes** [comment]
Yes, I agree. Why don't you do this per capita and show me what it looks like?

**Comment by JosephBARBIERDARNAL** [comment]
I'll do that!

**Comment by JosephBARBIERDARNAL** [comment]
Animation still not very effective @dgkeyes 

![animated_refugee_map](https://github.com/user-attachments/assets/19465f53-d6b5-403d-a667-8ed7b6b5eb66)

The fact is that a few countries have the highest number of refugees, so a global choropleth map may not be the best way to visualize the situation. One of their graphs highlights this:

<img width="886" alt="Screenshot 2024-10-28 at 08 53 13" src="https://github.com/user-attachments/assets/ecba48b0-b9d9-4bbc-a246-f1f91f64e445">

**Comment by dgkeyes** [comment]
Hmm, ok. Is the code for this up to date in the branch? I'll take a look at it.
